### PR TITLE
Fix encryption string/unicode bug https://bugs.launchpad.net/pypdf/+bug/2

### PR DESCRIPTION
**Pull request by harobed**
Fix encryption string/unicode bug https://bugs.launchpad.net/pypdf/+bug/242756

### CODE REVIEW

**Comment by harobed** [comment]
Can you also push « Add user access permissions feature to encrypt method » changeset ?

**Comment by jnweiger** [comment]
Pulling this fix into openSUSE (obs sr#148198). It clearly fixes a bug and the patch appears clean to me.
Upstream, please consider accepting this pull request.

**Comment by mfenniak** [comment]
Hi. I'm no longer maintaining pyPdf, but the project has been forked as pyPdf2 and is being maintained under that new name. (https://github.com/knowah/PyPDF2/)  I hope that the new maintainer can help you out.

**Comment by jnweiger** [comment]
Okay, the fix is already there. Thanks.

**Pull request closed without merging**
